-- Old Runes localization

OldRunesUI = OldRunesUI or {}

local base = {
    ADDON_NAME = "Old Runes",

    CMD_HELP_TITLE = "Commands:",
    CMD_DESC_TIMER = "Toggle timer numbers",
    CMD_DESC_SPIRAL = "Toggle cooldown spiral",
    CMD_DESC_REVERSE = "Toggle reverse recovery order",
    CMD_DESC_PRD = "Toggle old personal resource display",
    CMD_DESC_STYLE_SPEC = "Spec-based rune style",
    CMD_DESC_STYLE_MIXED = "Mixed rune style",
    CMD_DESC_STYLE_DEATH = "Death rune style",
    CMD_DESC_STYLE_SPECLESS = "Blizzard specless (gray) rune style",
    CMD_DESC_MULTICOLOR = "Legacy alias for mixed style toggle",
    CMD_DESC_CONFIG = "Open settings",

    MSG_TIMER = "Timer",
    MSG_COOLDOWN_SPIRAL = "Cooldown spiral",
    MSG_REVERSE_RECOVERY = "Reverse recovery",
    MSG_OLD_PRD = "Old personal resource display",
    MSG_STYLE_SET = "Style set to %s",
    MSG_STYLE_USAGE = "Usage /or style spec|mixed|death|specless",
    MSG_SETTINGS_NOT_READY = "Settings not registered yet. Reload UI.",

    STATE_ON = "ON",
    STATE_OFF = "OFF",

    STYLE_NAME_SPEC = "Spec",
    STYLE_NAME_MIXED = "Mixed",
    STYLE_NAME_DEATH = "Death",
    STYLE_NAME_SPECLESS = "Specless",

    OPT_SUBTITLE = "Customize Death Knight rune appearance (classic design)",
    OPT_TIMER_LABEL = "Show cooldown timer numbers",
    OPT_TIMER_TT = "Display countdown numbers on rune cooldowns",
    OPT_SPIRAL_LABEL = "Show cooldown spiral",
    OPT_SPIRAL_TT = "Use the standard cooldown spiral for rune recovery",
    OPT_REVERSE_LABEL = "Reverse rune recovery order",
    OPT_REVERSE_TT = "Reverses visual recovery direction (right to left)",
    OPT_PRD_LABEL = "Old Personal Resource Display",
    OPT_PRD_TT = "Apply Old Runes styling to the personal resource display (prdClassFrame)",
    OPT_STYLE_LABEL = "Rune style",
    OPT_STYLE_SPEC_LABEL = "Spec (Blood/Frost/Unholy)",
    OPT_STYLE_SPEC_TT = "Rune color follows your current specialization",
    OPT_STYLE_MIXED_LABEL = "Mixed (Blood, Frost, Unholy)",
    OPT_STYLE_MIXED_TT = "Always shows classic mixed set by slot order",
    OPT_STYLE_DEATH_LABEL = "Death (all runes as Death)",
    OPT_STYLE_DEATH_TT = "Uses Death rune style for all rune slots",
    OPT_STYLE_SPECLESS_LABEL = "Specless (Blizzard gray atlas)",
    OPT_STYLE_SPECLESS_TT = "Uses Blizzard's gray pre-specialization rune atlas",
}

local locales = {
    ruRU = {
        CMD_HELP_TITLE = "Команды:",
        CMD_DESC_TIMER = "Переключить цифры таймера",
        CMD_DESC_SPIRAL = "Переключить спираль восстановления",
        CMD_DESC_REVERSE = "Переключить обратный порядок восстановления",
        CMD_DESC_PRD = "Переключить старый личный индикатор ресурса",
        CMD_DESC_STYLE_SPEC = "Стиль рун по специализации",
        CMD_DESC_STYLE_MIXED = "Смешанный стиль рун",
        CMD_DESC_STYLE_DEATH = "Стиль рун смерти",
        CMD_DESC_STYLE_SPECLESS = "Стиль specless (серые руны Blizzard)",
        CMD_DESC_MULTICOLOR = "Устаревший алиас для mixed-стиля",
        CMD_DESC_CONFIG = "Открыть настройки",

        MSG_TIMER = "Таймер",
        MSG_COOLDOWN_SPIRAL = "Спираль восстановления",
        MSG_REVERSE_RECOVERY = "Обратный порядок восстановления",
        MSG_OLD_PRD = "Старый личный индикатор ресурса",
        MSG_STYLE_SET = "Стиль установлен: %s",
        MSG_STYLE_USAGE = "Использование: /or style spec|mixed|death|specless",
        MSG_SETTINGS_NOT_READY = "Настройки еще не зарегистрированы. Перезагрузите интерфейс.",

        STATE_ON = "ВКЛ",
        STATE_OFF = "ВЫКЛ",

        STYLE_NAME_SPEC = "По специализации",
        STYLE_NAME_MIXED = "Смешанный",
        STYLE_NAME_DEATH = "Смерть",
        STYLE_NAME_SPECLESS = "Specless",

        OPT_SUBTITLE = "Настройка внешнего вида рун рыцаря смерти (классический стиль)",
        OPT_TIMER_LABEL = "Показывать цифры таймера восстановления",
        OPT_TIMER_TT = "Показывать числовой отсчет восстановления рун",
        OPT_SPIRAL_LABEL = "Показывать спираль восстановления",
        OPT_SPIRAL_TT = "Использовать стандартную спираль восстановления рун",
        OPT_REVERSE_LABEL = "Обратный порядок восстановления рун",
        OPT_REVERSE_TT = "Разворачивает визуальное восстановление справа налево",
        OPT_PRD_LABEL = "Старый личный индикатор ресурса",
        OPT_PRD_TT = "Применять стиль Old Runes к личному индикатору ресурса (prdClassFrame)",
        OPT_STYLE_LABEL = "Стиль рун",
        OPT_STYLE_SPEC_LABEL = "По специализации (Blood/Frost/Unholy)",
        OPT_STYLE_SPEC_TT = "Цвет рун зависит от текущей специализации",
        OPT_STYLE_MIXED_LABEL = "Смешанный (Blood, Frost, Unholy)",
        OPT_STYLE_MIXED_TT = "Всегда показывает классический смешанный набор",
        OPT_STYLE_DEATH_LABEL = "Смерть (все руны как Death)",
        OPT_STYLE_DEATH_TT = "Использует стиль рун смерти для всех слотов",
        OPT_STYLE_SPECLESS_LABEL = "Specless (серый атлас Blizzard)",
        OPT_STYLE_SPECLESS_TT = "Использует серый атлас Blizzard до выбора специализации",
    },
    esES = {
        CMD_HELP_TITLE = "Comandos:",
        CMD_DESC_TIMER = "Alternar números del temporizador",
        CMD_DESC_SPIRAL = "Alternar espiral de reutilización",
        CMD_DESC_REVERSE = "Alternar orden inverso de recuperación",
        CMD_DESC_PRD = "Alternar recurso personal clásico",
        CMD_DESC_STYLE_SPEC = "Estilo por especialización",
        CMD_DESC_STYLE_MIXED = "Estilo mixto",
        CMD_DESC_STYLE_DEATH = "Estilo de runa de muerte",
        CMD_DESC_STYLE_SPECLESS = "Estilo specless (gris de Blizzard)",
        CMD_DESC_MULTICOLOR = "Alias heredado para alternar estilo mixto",
        CMD_DESC_CONFIG = "Abrir ajustes",

        MSG_TIMER = "Temporizador",
        MSG_COOLDOWN_SPIRAL = "Espiral de reutilización",
        MSG_REVERSE_RECOVERY = "Recuperación inversa",
        MSG_OLD_PRD = "Recurso personal clásico",
        MSG_STYLE_SET = "Estilo establecido: %s",
        MSG_STYLE_USAGE = "Uso: /or style spec|mixed|death|specless",
        MSG_SETTINGS_NOT_READY = "Los ajustes aún no están registrados. Recarga la interfaz.",

        STATE_ON = "ACTIVADO",
        STATE_OFF = "DESACTIVADO",

        STYLE_NAME_SPEC = "Especialización",
        STYLE_NAME_MIXED = "Mixto",
        STYLE_NAME_DEATH = "Muerte",
        STYLE_NAME_SPECLESS = "Specless",

        OPT_SUBTITLE = "Personaliza la apariencia de las runas del Caballero de la Muerte (estilo clásico)",
        OPT_TIMER_LABEL = "Mostrar números del temporizador",
        OPT_TIMER_TT = "Muestra la cuenta regresiva en la recuperación de runas",
        OPT_SPIRAL_LABEL = "Mostrar espiral de reutilización",
        OPT_SPIRAL_TT = "Usa la espiral estándar para la recuperación de runas",
        OPT_REVERSE_LABEL = "Invertir orden de recuperación de runas",
        OPT_REVERSE_TT = "Invierte la dirección visual de recuperación (de derecha a izquierda)",
        OPT_PRD_LABEL = "Recurso personal clásico",
        OPT_PRD_TT = "Aplica el estilo Old Runes al recurso personal (prdClassFrame)",
        OPT_STYLE_LABEL = "Estilo de runas",
        OPT_STYLE_SPEC_LABEL = "Especialización (Blood/Frost/Unholy)",
        OPT_STYLE_SPEC_TT = "El color de runa sigue tu especialización actual",
        OPT_STYLE_MIXED_LABEL = "Mixto (Blood, Frost, Unholy)",
        OPT_STYLE_MIXED_TT = "Muestra siempre el conjunto mixto clásico",
        OPT_STYLE_DEATH_LABEL = "Muerte (todas como Death)",
        OPT_STYLE_DEATH_TT = "Usa estilo de runa de muerte para todas las runas",
        OPT_STYLE_SPECLESS_LABEL = "Specless (atlas gris de Blizzard)",
        OPT_STYLE_SPECLESS_TT = "Usa el atlas gris de runas de Blizzard previo a especialización",
    },
    esMX = {
        CMD_HELP_TITLE = "Comandos:",
        CMD_DESC_TIMER = "Alternar números del temporizador",
        CMD_DESC_SPIRAL = "Alternar espiral de reutilización",
        CMD_DESC_REVERSE = "Alternar orden inverso de recuperación",
        CMD_DESC_PRD = "Alternar recurso personal clásico",
        CMD_DESC_STYLE_SPEC = "Estilo por especialización",
        CMD_DESC_STYLE_MIXED = "Estilo mixto",
        CMD_DESC_STYLE_DEATH = "Estilo de runa de muerte",
        CMD_DESC_STYLE_SPECLESS = "Estilo specless (gris de Blizzard)",
        CMD_DESC_MULTICOLOR = "Alias heredado para alternar estilo mixto",
        CMD_DESC_CONFIG = "Abrir ajustes",

        MSG_TIMER = "Temporizador",
        MSG_COOLDOWN_SPIRAL = "Espiral de reutilización",
        MSG_REVERSE_RECOVERY = "Recuperación inversa",
        MSG_OLD_PRD = "Recurso personal clásico",
        MSG_STYLE_SET = "Estilo establecido: %s",
        MSG_STYLE_USAGE = "Uso: /or style spec|mixed|death|specless",
        MSG_SETTINGS_NOT_READY = "Los ajustes aún no están registrados. Recarga la interfaz.",

        STATE_ON = "ACTIVADO",
        STATE_OFF = "DESACTIVADO",

        STYLE_NAME_SPEC = "Especialización",
        STYLE_NAME_MIXED = "Mixto",
        STYLE_NAME_DEATH = "Muerte",
        STYLE_NAME_SPECLESS = "Specless",

        OPT_SUBTITLE = "Personaliza la apariencia de las runas del Caballero de la Muerte (estilo clásico)",
        OPT_TIMER_LABEL = "Mostrar números del temporizador",
        OPT_TIMER_TT = "Muestra la cuenta regresiva en la recuperación de runas",
        OPT_SPIRAL_LABEL = "Mostrar espiral de reutilización",
        OPT_SPIRAL_TT = "Usa la espiral estándar para la recuperación de runas",
        OPT_REVERSE_LABEL = "Invertir orden de recuperación de runas",
        OPT_REVERSE_TT = "Invierte la dirección visual de recuperación (de derecha a izquierda)",
        OPT_PRD_LABEL = "Recurso personal clásico",
        OPT_PRD_TT = "Aplica el estilo Old Runes al recurso personal (prdClassFrame)",
        OPT_STYLE_LABEL = "Estilo de runas",
        OPT_STYLE_SPEC_LABEL = "Especialización (Blood/Frost/Unholy)",
        OPT_STYLE_SPEC_TT = "El color de runa sigue tu especialización actual",
        OPT_STYLE_MIXED_LABEL = "Mixto (Blood, Frost, Unholy)",
        OPT_STYLE_MIXED_TT = "Muestra siempre el conjunto mixto clásico",
        OPT_STYLE_DEATH_LABEL = "Muerte (todas como Death)",
        OPT_STYLE_DEATH_TT = "Usa estilo de runa de muerte para todas las runas",
        OPT_STYLE_SPECLESS_LABEL = "Specless (atlas gris de Blizzard)",
        OPT_STYLE_SPECLESS_TT = "Usa el atlas gris de runas de Blizzard previo a especialización",
    },
    zhCN = {
        CMD_HELP_TITLE = "命令：",
        CMD_DESC_TIMER = "切换冷却数字倒计时",
        CMD_DESC_SPIRAL = "切换冷却螺旋",
        CMD_DESC_REVERSE = "切换反向恢复顺序",
        CMD_DESC_PRD = "切换旧版个人资源显示",
        CMD_DESC_STYLE_SPEC = "专精样式",
        CMD_DESC_STYLE_MIXED = "混合样式",
        CMD_DESC_STYLE_DEATH = "死亡符文样式",
        CMD_DESC_STYLE_SPECLESS = "无专精样式（暴雪灰色）",
        CMD_DESC_MULTICOLOR = "旧版 mixed 样式切换别名",
        CMD_DESC_CONFIG = "打开设置",

        MSG_TIMER = "计时器",
        MSG_COOLDOWN_SPIRAL = "冷却螺旋",
        MSG_REVERSE_RECOVERY = "反向恢复",
        MSG_OLD_PRD = "旧版个人资源显示",
        MSG_STYLE_SET = "样式已设置为：%s",
        MSG_STYLE_USAGE = "用法：/or style spec|mixed|death|specless",
        MSG_SETTINGS_NOT_READY = "设置尚未注册，请重载界面。",

        STATE_ON = "开启",
        STATE_OFF = "关闭",

        STYLE_NAME_SPEC = "专精",
        STYLE_NAME_MIXED = "混合",
        STYLE_NAME_DEATH = "死亡",
        STYLE_NAME_SPECLESS = "无专精",

        OPT_SUBTITLE = "自定义死亡骑士符文外观（经典风格）",
        OPT_TIMER_LABEL = "显示冷却数字倒计时",
        OPT_TIMER_TT = "在符文冷却时显示数字倒计时",
        OPT_SPIRAL_LABEL = "显示冷却螺旋",
        OPT_SPIRAL_TT = "使用标准螺旋冷却显示符文恢复",
        OPT_REVERSE_LABEL = "反向符文恢复顺序",
        OPT_REVERSE_TT = "将恢复方向反转为从右到左",
        OPT_PRD_LABEL = "旧版个人资源显示",
        OPT_PRD_TT = "将 Old Runes 样式应用到个人资源显示（prdClassFrame）",
        OPT_STYLE_LABEL = "符文样式",
        OPT_STYLE_SPEC_LABEL = "专精（Blood/Frost/Unholy）",
        OPT_STYLE_SPEC_TT = "符文颜色跟随当前专精",
        OPT_STYLE_MIXED_LABEL = "混合（Blood, Frost, Unholy）",
        OPT_STYLE_MIXED_TT = "始终显示经典混合符文",
        OPT_STYLE_DEATH_LABEL = "死亡（全部为 Death）",
        OPT_STYLE_DEATH_TT = "所有符文使用死亡符文样式",
        OPT_STYLE_SPECLESS_LABEL = "无专精（暴雪灰色图集）",
        OPT_STYLE_SPECLESS_TT = "使用暴雪未选专精时的灰色符文图集",
    },
    zhTW = {
        CMD_HELP_TITLE = "指令：",
        CMD_DESC_TIMER = "切換冷卻數字倒數",
        CMD_DESC_SPIRAL = "切換冷卻螺旋",
        CMD_DESC_REVERSE = "切換反向恢復順序",
        CMD_DESC_PRD = "切換舊版個人資源顯示",
        CMD_DESC_STYLE_SPEC = "專精樣式",
        CMD_DESC_STYLE_MIXED = "混合樣式",
        CMD_DESC_STYLE_DEATH = "死亡符文樣式",
        CMD_DESC_STYLE_SPECLESS = "無專精樣式（暴雪灰色）",
        CMD_DESC_MULTICOLOR = "舊版 mixed 樣式切換別名",
        CMD_DESC_CONFIG = "開啟設定",

        MSG_TIMER = "計時器",
        MSG_COOLDOWN_SPIRAL = "冷卻螺旋",
        MSG_REVERSE_RECOVERY = "反向恢復",
        MSG_OLD_PRD = "舊版個人資源顯示",
        MSG_STYLE_SET = "樣式已設為：%s",
        MSG_STYLE_USAGE = "用法：/or style spec|mixed|death|specless",
        MSG_SETTINGS_NOT_READY = "設定尚未註冊，請重新載入介面。",

        STATE_ON = "開啟",
        STATE_OFF = "關閉",

        STYLE_NAME_SPEC = "專精",
        STYLE_NAME_MIXED = "混合",
        STYLE_NAME_DEATH = "死亡",
        STYLE_NAME_SPECLESS = "無專精",

        OPT_SUBTITLE = "自訂死亡騎士符文外觀（經典風格）",
        OPT_TIMER_LABEL = "顯示冷卻數字倒數",
        OPT_TIMER_TT = "在符文冷卻時顯示數字倒數",
        OPT_SPIRAL_LABEL = "顯示冷卻螺旋",
        OPT_SPIRAL_TT = "使用標準螺旋冷卻顯示符文恢復",
        OPT_REVERSE_LABEL = "反向符文恢復順序",
        OPT_REVERSE_TT = "將恢復方向反轉為由右到左",
        OPT_PRD_LABEL = "舊版個人資源顯示",
        OPT_PRD_TT = "將 Old Runes 樣式套用到個人資源顯示（prdClassFrame）",
        OPT_STYLE_LABEL = "符文樣式",
        OPT_STYLE_SPEC_LABEL = "專精（Blood/Frost/Unholy）",
        OPT_STYLE_SPEC_TT = "符文顏色跟隨目前專精",
        OPT_STYLE_MIXED_LABEL = "混合（Blood, Frost, Unholy）",
        OPT_STYLE_MIXED_TT = "永遠顯示經典混合符文",
        OPT_STYLE_DEATH_LABEL = "死亡（全部為 Death）",
        OPT_STYLE_DEATH_TT = "所有符文使用死亡符文樣式",
        OPT_STYLE_SPECLESS_LABEL = "無專精（暴雪灰色圖集）",
        OPT_STYLE_SPECLESS_TT = "使用暴雪未選專精時的灰色符文圖集",
    },
}

local selected = locales[GetLocale()] or {}
OldRunesUI.L = setmetatable(selected, { __index = base })
